### ISSUE TITLE
PSK+

### ISSUE THREAD

**Issue by JosefJezek** [limhenry/io16mmu#1]
Could you this template based on PSK+ Lite?
- https://github.com/StartPolymer/polymer-starter-kit-plus
- https://github.com/StartPolymer/polymer-starter-kit-plus/tree/lite

**Comment by limhenry** [comment]
> _Could you this template based on PSK+ Lite?_ 

@JosefJezek What do you mean? I am not really understand that... :confused:

**Comment by JosefJezek** [comment]
Check it out this project...

https://github.com/gdg-x/hoverboard

**Comment by limhenry** [comment]
Sure. I will try :smile: Or maybe you could help me too?
Thanks for the suggestion @JosefJezek

**Comment by limhenry** [comment]
Hey @JosefJezek, check out this repo [https://github.com/limhenry/cerium](https://github.com/limhenry/cerium)
